### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by celsojr** [WaveEngine/LowLevelAPIDemo#1]
Sorry, just to say that there is an extra `w` over there.
![extra_w](https://user-images.githubusercontent.com/6450642/110262438-703e0e80-7f92-11eb-9d26-fd23330fafe1.png)

By the way, I just tested these examples on Ubuntu 20.10 and they all work like a charm. Congrats!

**Comment by vicfergar** [comment]
Hi @celsojr,

Thanks for the feedback, it has been fixed now.
